name: test-and-docs

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - release-please
    types:
      - complete

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: docsgen
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: install pip deps
        run: |
          python -m pip install myst-parser pydata-sphinx-theme sphinx-lua sphinx-press-theme
      - name: Build docs
        shell: bash
        run: |
          make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
