name: generate-docs

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - release-please
    types:
      - complete

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: docsgen
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        shell: bash
        with:
          python-version: '3.11'
          cache: 'pip'
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      - name: Build docs
        shell: bash
        run: |
          cat "$GITHUB_PATH"
          echo "$PATH"
          ls -la "$HOME/.local/bin"
          PATH="$PATH:$(python3 -m site --user-base)/bin" make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
